config/routes.rb
CantangoDemo::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :posts
  resources :projects

  root :to => 'application#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  tango_user
end

app/models/guest.rb
class Guest
  extend  ActiveModel::Naming
  include ActiveModel::Conversion
  include ActiveModel::Validations

  def initialize
    # basic config of guest user!
  end

  def email
    'guest@info.com'
  end

  def create options = {}
    # new instance and set valid attributes?
  end

  def has_role? role
    role.to_sym == :guest
  end

  def persisted?
    false
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  def self.guest
    Guest.new
  end

  tango_user

  troles_strategy :bit_many do |config|
    config.valid_roles = [:editor, :publisher, :basic]
  end.configure!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  extend CanTango::Api::UserAccount::Ability

  protect_from_forgery

  def index
  end

  # used by CanCan for authorize! resource
  def current_ability
    @current_ability ||= current_user_ability :admin_user
  end

  def current_user
    current_admin_user
  end

  before_filter :set_timezone
  def set_timezone
    Time.zone = current_user.time_zone if current_user and !current_user.time_zone.blank?
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  respond_to :html

  expose(:posts) { Post.all }
  expose(:post)

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    post.save ? redirect_to(project, notice: 'Post was successfully created.') : render(action: "new")
  end

  def update
    update_attributes ? redirect_to(post, notice: 'Post was successfully updated.') : render(action: "edit")
  end

  def destroy
    post.destroy
    redirect_to posts_url
  end

  private

  def update_attributes
    post.update_attributes(params[:post])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  respond_to :html

  expose(:projects) { Project.all }
  expose(:project)

  def index
  end

  def show
  end

  def new
  end

  def edit
  end

  def create
    project.save ? redirect_to(project, notice: 'Project was successfully created.') : render(action: "new")
  end

  def update
    update_attributes ? redirect_to(project, notice: 'Project was successfully updated.' : render(action: "edit")
  end

  def destroy
    project.destroy
    redirect_to projects_url
  end

  private

  def update_attributes
    project.update_attributes(params[:project])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/application/index.html.haml
%h1 Welcome to the CanTango Demo

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title My App
    = stylesheet_link_tag :application
    = javascript_include_tag :application
    = csrf_meta_tags
  %body
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)
    = yield

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_field :desc %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br />
    <%= f.number_field :author_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Desc</th>
    <th>Author</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.title %></td>
    <td><%= post.desc %></td>
    <td><%= post.author_id %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Desc:</b>
  <%= @post.desc %>
</p>

<p>
  <b>Author:</b>
  <%= @post.author_id %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>